services:
    php:
        build:
            target: frankenphp_dev
        volumes:
            - build:/app/public/build
            - node_modules:/app/node_modules
            - var:/app/var
            - vendor:/app/vendor
            - ./config/docker/php.dev.ini:/usr/local/etc/php/conf.d/30-php.ini
            - ./config/docker/php.ini:/usr/local/etc/php/conf.d/20-php.ini
            - .:/app
        environment:
            CADDY_GLOBAL_OPTIONS: debug
            SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
            DATABASE_URL: mysql://${MARIADB_USER:-app}:${MARIADB_PASSWORD:-!ChangeMe!}@db:3306/${MARIADB_DATABASE:-app}?charset=${MARIADB_CHARSET:-utf8}
            MAILER_DSN: smtp://mailpit:1025

    php-worker:
        extends:
            service: php
        volumes:
            - ./config/docker/supervisor.conf:/etc/supervisor/conf.d/app.conf

    db:
        environment:
            MARIADB_USER: ${MARIADB_USER:-app}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
            MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-!ChangeMe!}

    mailpit:
        container_name: ${COMPOSE_PROJECT_NAME}-mailpit
        image: axllent/mailpit:latest
        ports:
            - 8025:8025
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: true
            MP_SMTP_AUTH_ALLOW_INSECURE: true
        restart: unless-stopped

volumes:
    build:
    node_modules:
    var:
    vendor:
