services:
    php:
        container_name: ${COMPOSE_PROJECT_NAME}-php
        build:
            target: frankenphp_prod
        volumes:
            - php-config:/config
            - php-data:/data
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        restart: unless-stopped

    php-worker:
        extends:
            service: php
        container_name: ${COMPOSE_PROJECT_NAME}-php-worker
        ports: !reset []
        command: ['bash', '-c', '/usr/bin/supervisord -c /etc/supervisor/supervisord.conf']
        restart: unless-stopped

    db:
        container_name: ${COMPOSE_PROJECT_NAME}-db
        image: mariadb:latest
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        restart: unless-stopped

    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            PMA_ARBITRARY: true
            PMA_HOST: db
            UPLOAD_LIMIT: 5M
        restart: unless-stopped

volumes:
    php-config:
    php-data:
    db-data:
